const products = [
  // Bicicletas
  {
    id: 1,
    name: "Bicicleta MTB Ozz Trail Pro",
    price: 450000,
    category: "bicicletas",
    image: "/placeholder.svg?height=300&width=300",
    description: "Bicicleta de montaña profesional con suspensión completa",
    inStock: true,
    rating: 4.8,
    featured: true,
  },
  {
    id: 2,
    name: "Bicicleta Urbana Ozz City",
    price: 280000,
    category: "bicicletas",
    image: "/placeholder.svg?height=300&width=300",
    description: "Perfecta para la ciudad, cómoda y elegante",
    inStock: true,
    rating: 4.6,
  },
  {
    id: 3,
    name: "Bicicleta Ruta Ozz Speed",
    price: 520000,
    category: "bicicletas",
    image: "/placeholder.svg?height=300&width=300",
    description: "Bicicleta de ruta para competición y entrenamiento",
    inStock: false,
    rating: 4.9,
  },

  // Indumentaria
  {
    id: 4,
    name: "Jersey Ozz Pro Team",
    price: 45000,
    category: "indumentaria",
    image: "/placeholder.svg?height=300&width=300",
    description: "Jersey profesional con tecnología de secado rápido",
    inStock: true,
    rating: 4.7,
    featured: true,
  },
  {
    id: 5,
    name: "Culotte Ozz Comfort",
    price: 38000,
    category: "indumentaria",
    image: "/placeholder.svg?height=300&width=300",
    description: "Culotte con badana de gel para máximo confort",
    inStock: true,
    rating: 4.8,
  },
  {
    id: 6,
    name: "Casco Ozz Safety Pro",
    price: 85000,
    category: "indumentaria",
    image: "/placeholder.svg?height=300&width=300",
    description: "Casco ultraliviano con certificación internacional",
    inStock: true,
    rating: 4.9,
  },

  // Accesorios
  {
    id: 7,
    name: "Luces LED Ozz Night",
    price: 25000,
    category: "accesorios",
    image: "/placeholder.svg?height=300&width=300",
    description: "Set de luces LED recargables para mayor seguridad",
    inStock: true,
    rating: 4.5,
  },
  {
    id: 8,
    name: "Candado Ozz Security",
    price: 32000,
    category: "accesorios",
    image: "/placeholder.svg?height=300&width=300",
    description: "Candado de alta seguridad con cable de acero",
    inStock: true,
    rating: 4.6,
  },
  {
    id: 9,
    name: "Bomba Ozz Pro Pump",
    price: 18000,
    category: "accesorios",
    image: "/placeholder.svg?height=300&width=300",
    description: "Bomba portátil con manómetro integrado",
    inStock: true,
    rating: 4.7,
  },

  // Lavado
  {
    id: 10,
    name: "Kit Limpieza Ozz Clean",
    price: 22000,
    category: "lavado",
    image: "/placeholder.svg?height=300&width=300",
    description: "Kit completo para limpieza y mantenimiento",
    inStock: true,
    rating: 4.4,
  },
  {
    id: 11,
    name: "Desengrasante Ozz Pro",
    price: 12000,
    category: "lavado",
    image: "/placeholder.svg?height=300&width=300",
    description: "Desengrasante biodegradable de alta efectividad",
    inStock: true,
    rating: 4.5,
  },
  {
    id: 12,
    name: "Lubricante Cadena Ozz",
    price: 8000,
    category: "lavado",
    image: "/placeholder.svg?height=300&width=300",
    description: "Lubricante especial para cadenas y componentes",
    inStock: false,
    rating: 4.6,
  },
]

export default products
