const products = [
  // Bicicletas
  {
    id: 1,
    name: "Continental Grand Prix 5000 Banda Crema",
    price: 450000,
    category: "bicicletas",
    image: "/OZZimages/productos/product1.jpg",
    description: "La nueva era en el ciclismo. Montá más rápido, más cómodo y con una mayor protección contra pinchazos.\n\nDiseñado para hacerte mejorar",
    inStock: true,
    rating: 4.8,
    featured: true,
  },
  {
    id: 2,
    name: "Pata CeramicSpeed OSPW 🚴🏻",
    price: 280000,
    category: "bicicletas",
    image: "/OZZimages/productos/product2.jpg",
    description: "Los componentes CeramicSpeed están diseñados con la velocidad en mente y están construidos para llevarte más rápido y más lejos de lo que jamás imaginaste",
    inStock: true,
    rating: 4.6,
  },
  {
    id: 3,
    name: "Inflador de mano Lezyne Gauge Drive Hp con manómetro 🙌🏼",
    price: 520000,
    category: "accesorios",
    image: "/OZZimages/productos/product3.jpg",
    description: "Inflador portátil compacto y liviano, con eficiente mango de material compuesto.\n\nConstruido en aluminio CNC con tratamiento especial para aplicaciones de alta presión.",
    inStock: true,
    rating: 4.9,
  },
  {
    id: 15,
    name: "SHIMANO DEORE M6100 MTB 12V",
    price: 0,
    category: "bicicletas",
    image: "/OZZimages/productos/bicigw3.webp",
    description: "▫️12 velocidades\n▫️Ruedas: SHIMANO MT-601 • 29 pulgadas\n▫️Frenos: SHIMANO MT-200\n▫️Horquilla de aire con bloqueo remoto",
    inStock: true,
    rating: 4.8,
  },
  {
    id: 16,
    name: "Cannondale Trail 7 MTB",
    price: 0,
    category: "bicicletas",
    images: [
      "/OZZimages/productos/CannondaleTrail7.jpg",
      "/OZZimages/bicis/trail7.jpg"
    ],
    image: "/OZZimages/productos/CannondaleTrail7.jpg",
    description: "Cannondale Trail 7. Una bicicleta de montaña construida para elevar tu juego y encender una pasión por el sendero.\n\nDiseñada para las montañas y lista para cualquier cosa.",
    inStock: true,
    rating: 4.8,
  },
  {
    id: 17,
    name: "Cubierta Vittoria Rubino Pro",
    price: 0,
    category: "bicicletas",
    image: "/OZZimages/productos/cub1.jpg",
    description: "Cubierta Vittoria Rubino Pro para entrenamiento — Diseñado para entrenamiento intensivo e igualmente adecuado para eventos de carreras. Larga vida útil, protección contra pinchazos y características de manejo nítidas. ¡El Rubino Pro más versátil que nunca!",
    inStock: true,
    rating: 4.7,
  },
  {
    id: 18,
    name: "Ruedas B Team Carbono 60mm",
    price: 0,
    category: "bicicletas",
    image: "/OZZimages/productos/rued1.jpg",
    description: "RUEDAS B TEAM — FIBRA DE CARBONO • 24 rayos rueda delantera y trasera • Perfil 60mm • Eje pasante 120mm • Tubeless-ready ¡Realizamos envíos a todo el país!",
    inStock: true,
    rating: 4.8,
  },
  {
    id: 19,
    name: "PINARELLO DOGMA F Ultegra Di2 R8170",
    price: 0,
    category: "bicicletas",
    images: [
      "/OZZimages/productos/PINARE.jpg",
      "/OZZimages/productos/pinare2.jpg"
    ],
    image: "/OZZimages/productos/PINARE.jpg",
    description: "PINARELLO DOGMA F — Shimano Ultegra Di2 R8170 — 12 velocidades con ruedas Shimano Ultegra C50. Dogma F es la combinación de cada experiencia, gusto, instinto, habilidad y saber hacer. La bicicleta ideal para todo ciclista y cualquier tipo de ruta. Conseguila en OZZ CYCLING.",
    inStock: true,
    rating: 4.9,
  },
  {
    id: 22,
    name: "Cannondale Adventure",
    price: 0,
    category: "bicicletas",
    image: "/OZZimages/bicis/bicidiver.webp",
    description: "Una bicicleta divertida para andar, Cannondale Adventure es la opción perfecta cuando se tiene al comfort como prioridad.",
    inStock: true,
    rating: 4.7,
  },
  
  {
    id: 4,
    name: "CeramicSpeed OPWS (Oversized Pulley Wheel Systems)",
    price: 45000,
    category: "bicicletas",
    image: "/OZZimages/productos/product4.jpg",
    description: "Mejorá significativamente tu rendimiento y la eficiencia de tu bicicleta con CeramicSpeed y los sistemas OPWS (Oversized Pulley Wheel Systems). Los rodamientos CeramicSpeed se destacan por su bajo coeficiente de fricción y su durabilidad.",
    inStock: true,
    rating: 4.7,
    featured: true,
  },
  {
    id: 5,
    name: "Palanca de Freno DURA-ACE",
    price: 38000,
    category: "bicicletas",
    image: "/OZZimages/productos/product5.jpg",
    description: "Palanca de freno de alta gama para bicicletas, marca DURA-ACE. Precisión y rendimiento profesional en cada frenada.",
    inStock: true,
    rating: 4.8,
  },
  {
    id: 6,
    name: "Descarrilador de Cambios DURA-ACE",
    price: 85000,
    category: "bicicletas",
    image: "/OZZimages/productos/product6.jpg",
    description: "Descarrilador de cambios de alta precisión para bicicletas, marca DURA-ACE. Cambios suaves y confiables para ciclistas exigentes.",
    inStock: true,
    rating: 4.9,
  },
  {
    id: 20,
    name: "Casco OCTAL X SPIN",
    price: 0,
    category: "accesorios",
    image: "/OZZimages/productos/CascoOCTALXSPIN.jpg",
    description: "Una carcasa extendida brinda a los ciclistas una protección adicional en un casco altamente ventilado.",
    inStock: true,
    rating: 4.7,
  },
  {
    id: 21,
    name: "CALZA AERO 3",
    price: 0,
    category: "indumentaria",
    image: "/OZZimages/productos/CALZAAERO3.jpg",
    description: "Conseguí tu ropa MAGENTA en Ozz Cycling.",
    inStock: true,
    rating: 4.6,
  },
  
  {
    id: 7,
    name: "Descarrilador Trasero DURA-ACE",
    price: 25000,
    category: "bicicletas",
    image: "/OZZimages/productos/product7.jpg",
    description: "Descarrilador trasero de alta gama para bicicletas, marca DURA-ACE. Precisión y durabilidad para el cambio de la rueda trasera.",
    inStock: true,
    rating: 4.5,
  },
  {
    id: 8,
    name: "Dura-Ace Di2",
    price: 32000,
    category: "bicicletas",
    image: "/OZZimages/productos/product8.jpg",
    description: "Componente electrónico de alta gama para bicicletas, sistema Dura-Ace Di2. Precisión y tecnología avanzada para el ciclismo profesional.",
    inStock: true,
    rating: 4.6,
  },
  {
    id: 9,
    name: "Corona de Bici DURA-ACE",
    price: 18000,
    category: "bicicletas",
    image: "/OZZimages/productos/product9.jpg",
    description: "Corona de bicicleta de alta gama, marca DURA-ACE. Máxima eficiencia y durabilidad para transmisión profesional.",
    inStock: true,
    rating: 4.7,
  },
  {
    id: 23,
    name: "Muc-Off",
    price: 0,
    category: "Lavado y Mantenimiento",
    image: "/OZZimages/productos/mucoof.jpg",
    description: "¿Conocés la marca #MucOff? La mejor referencia en productos para la limpieza y el mantenimiento de tu bicicleta 🚴‍♂️ Marca que cuenta con la confianza de ciclistas en lo más alto del escalafón del ciclismo mundial y la conseguís en OZZ Cycling",
    inStock: true,
    rating: 4.8,
  },
  {
    id: 24,
    name: "Cadenas Shimano",
    price: 0,
    category: "bicicletas",
    image: "/OZZimages/productos/cadenas.jpg",
    description: "Cadenas Shimano ⛓️ diseñadas para ser duraderas, confiables y ofrecer un cambio de marcha suave y preciso. Vienen en diferentes números de velocidad (desde 6 hasta 12), y están diseñadas para funcionar con otros componentes de transmisión Shimano para una experiencia de conducción óptima",
    inStock: true,
    rating: 4.8,
  },
  
  {
    id: 10,
    name: "Luces Lezyne",
    price: 22000,
    category: "accesorios",
    image: "/OZZimages/productos/product10.jpg",
    description: "¡Hacete ver con las luces Lezyne! Duran horas encendidas, resisten las lluvias y las caídas.",
    inStock: true,
    rating: 4.4,
  },
  {
    id: 11,
    name: "Garmin Edge 840 Solar",
    price: 12000,
    category: "accesorios",
    image: "/OZZimages/productos/product11.jpg",
    description: "Performance GPS cycling computer con mapeo, pantalla táctil y carga solar. Marca GARMIN, modelo EDGE 840.",
    inStock: true,
    rating: 4.5,
  },
  {
    id: 12,
    name: "Cubiertas Pirelli P Zero Race Tubeless Ready",
    price: 8000,
    category: "bicicletas",
    image: "/OZZimages/productos/product12.jpg",
    description: "Disponibles en 700x28 y 700x30. Tecnología exclusiva para carretera Smart Evo Compound y 120tpi para obtener la máxima velocidad con una gran adherencia.",
    inStock: false,
    rating: 4.6,
  },
  // Otros
  {
    id: 13,
    name: "Casco Kask Elemento y Zapatillas Shimano S-Phyre RC903",
    price: 99999,
    category: "accesorios",
    image: "/OZZimages/productos/product13.jpg",
    description: "El combo perfecto para vos: Casco Kask Elemento y zapatillas Shimano S-Phyre RC903. Disponible en nuestro local.",
    inStock: true,
    rating: 4.5,
  },
  {
    id: 14,
    name: "Zapatillas Shimano S-Phyre",
    price: 0,
    category: "accesorios",
    image: "/OZZimages/productos/Zapatillas.jpg",
    description: "Zapatillas Shimano S-Phyre disponibles para vos en Ozz Cycling.",
    inStock: true,
    rating: 4.7,
  },
]

export default products
